import './example/1/a1'
// import './example/2-basictype/basic'
// import './example/3-symbol/symbol'
// import './example/4-interface/interface'
// import './example/5-function/function'
// import './example/6-generics/generics'
// import './example/7-8-9-class/class'
// import './example/10-enum/enum'
// import './example/11-assert/assert'
// import './example/12-advanceType/advanceType'
